### PR TITLE
map to 4 (N) by default instead of only mapping N to 4 (and other ambiguity codes to 0, i.e. A)

### PR DESCRIPTION
**Pull request by gt1**
This pull request/patch slightly changes the character mapping in fasta2DB/fasta2DAM so it maps determinate bases (A,C,G,T and lower case variants) as usual and all other symbols to 4.

Background: some reference genomes (particularly the human one) contain ambiguity codes other than N (see e.g. http://www.boekhoff.info/?pid=data&dat=fasta-codes) and these should not be mapped like they were representing an A base.

### CODE REVIEW

**Comment by thegenemyers** [comment]
It seems to me this has got to screw things up, as how does one produce
base 4 k-mer codes with a 5 symbol mapping?  4 is used internally to denote
the end of a string, so I'd have to believe this change would blow up a lot
of things.  Does it really work downstream?  Have you checked?

    -- Gene

My thought is if you don't know what base it is, then an A is fine (or 
perhaps it
might be better to flip a coin).

**Comment by gt1** [comment]
No, the table used 4 symbols before, but just for N. Regions with N/4 
symbols are clipped out by fasta2DAM and fasta2DB. I see no issues due 
to this change downstream.

German

**Comment by gt1** [comment]
On closer inspection this just seems to hold for fasta2DAM. I'll take the patch out for fasta2DB.

**Comment by gt1** [comment]
Ok, so this is probably the wrong way to fix this problem, as the number of consecutive non N ambiguity codes in the human reference is low (1-3) so chromosomes should not be split at these. I'll implement a different approach to solve the original problem, which is how to map read ids from the dazzler database back to the sequence id in the original FastA file(s).

**Comment by thegenemyers** [comment]
The information on where a contig came from is stored in the data base.
This is evidenced by the fact that DAM2fasta produces the *original* 
reference
.fasta from the DAM.  Indeed for a given DAM contig HITS_READ *x, it 
came from
x->origin[x->fpulse..x->fpulse+x->rlen] in the original .fasta reference.
    Hope that helps,
       Gene

**Comment by gt1** [comment]
Thank you for the hint.

German

**Pull request closed without merging**
